[16.0] [MIG] hr_attendance_autoclose
OCA/hr-attendance pull request #116
Opened 2023-04-05 11:04 UTC by aleuffre

Depends on https://github.com/OCA/hr-attendance/pull/112

2023-09-05 15:27 UTC, tafaRU commented
/ocabot migration hr_attendance_autoclose

2023-10-16 07:18 UTC, tafaRU commented
@aleuffre thanks for your PR!
Looks good overall, but there are some commit generated by bots or weblate to be squashed (Ref. https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate).

2023-10-16 12:25 UTC, FratiuG approved these changes
functional test ok

2023-10-16 12:36 UTC, aleuffre commented
> @aleuffre thanks for your PR! Looks good overall, but there are some commit generated by bots or weblate to be squashed (Ref. https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests#mergesquash-the-commits-generated-by-bots-or-weblate).

Should be fine now

2023-10-17 16:05 UTC, tafaRU approved these changes

2023-10-18 07:19 UTC, tafaRU requested changes

2023-10-18 07:19 UTC, tafaRU commented on hr_attendance_autoclose/readme/USAGE.rst
> +#. Go to *Settings > Company > Attendances*.
This is no longer true, now we have:
![image](https://github.com/OCA/hr-attendance/assets/3512779/9bf4f460-02b0-4fbd-a00f-75802355565a)

Could you please modify it?

2023-10-18 10:04 UTC, tafaRU commented on hr_attendance_autoclose/readme/USAGE.rst
> +#. Go to *Attedances > Configuration > Configuration*.
s/Attedances/Attendances

2023-10-19 06:57 UTC, tafaRU approved these changes

2023-10-19 06:58 UTC, tafaRU commented
/ocabot merge nobump

2023-10-19 07:02 UTC, merged