[15.0][MIG] hr_attendance_rfid: Migration to 15.0
OCA/hr-attendance pull request #72
Opened 2022-08-29 07:06 UTC by victoralmau

Superseed https://github.com/OCA/hr-attendance/pull/66

Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT36462

2022-08-29 07:25 UTC, CarlosRoca13 requested changes

2022-08-29 07:25 UTC, CarlosRoca13 commented on hr_attendance_rfid/__manifest__.py
> +    "version": "15.0.1.1.0",
```suggestion
    "version": "15.0.1.0.0",
```

2022-08-29 07:28 UTC, CarlosRoca13 approved these changes

2022-08-29 15:16 UTC, pedrobaeza commented
/ocabot migration hr_attendance_rfid

2022-08-29 16:56 UTC, lubusax commented
I already improved the codecov using this test: 
(https://github.com/lubusax/hr-attendance/blob/74724f9ca1c65907c656827650c361cd224fb9a4/hr_attendance_rfid/tests/test_hr_attendance_rfid_process.py#L59)
I launched a PR on the same subject after you. Mine has been closed, but maybe you could reuse this test.

2022-08-30 06:23 UTC, victoralmau commented
> 

Ok, i have added the tests you indicate in a separate commit.

2022-09-07 02:31 UTC, nimarosa commented
Everyone it's okay with this migration?

2022-09-07 06:04 UTC, pedrobaeza commented
@nimarosa why don't you do a proper review?

2022-09-07 13:06 UTC, nimarosa commented
@pedrobaeza for me it's okay as this migration don't change any of the previous versión code. 

But as it has not been merged I wanted to know if anyone has any comment to do. 

I will test it in my instance today to be sure and we are ready. Also it's not much I can test since I have not a rfid device available to test. But will test installing and functional.

2022-09-07 20:06 UTC, lubusax commented
> @pedrobaeza for me it's okay as this migration don't change any of the previous versión code.
> 
> But as it has not been merged I wanted to know if anyone has any comment to do.
> 
> I will test it in my instance today to be sure and we are ready. Also it's not much I can test since I have not a rfid device available to test. But will test installing and functional.

Hi, I have installed the module and tried it on some RFID Attendance devices (I build and sell them myself). Works like a charm.

2022-09-07 20:11 UTC, pedrobaeza commented
/ocabot merge nobump

2022-09-07 20:15 UTC, merged