[15.0][MIG] hr_attendance_geolocation: Migration to 15.0
OCA/hr-attendance pull request #80
Opened 2022-11-04 09:45 UTC by victoralmau

Migration to 15.0

Please @pedrobaeza and @CarlosRoca13 can you review it?

@Tecnativa TT40358

2022-11-07 07:30 UTC, CarlosRoca13 approved these changes

2022-11-07 07:44 UTC, pedrobaeza commented
/ocabot migration hr_attendance_geolocation

2022-11-07 07:53 UTC, pedrobaeza requested changes
Tested in runboat, no geolocation permission is asked, nor any location logged on attendance check:

![Selección_004](https://user-images.githubusercontent.com/7165771/200254984-95bd3779-6783-4f17-8848-1ca9f74d78f1.png)

By the way, there's no visualization of the coordinates (I needed to put the fields on the list view). Maybe a couple of computed field putting them on human readable format and showing them on the list for the managers?

2022-11-07 09:56 UTC, nimarosa commented
It will be great if we can use a reverse geocoding library with this module, to show the address, and even better if we can show a map.

Just a suggestion, but I think this will be really useful if we have that.

2022-11-07 10:13 UTC, victoralmau commented
> 
> By the way, there's no visualization of the coordinates (I needed to put the fields on the list view). Maybe a couple of computed field putting them on human readable format and showing them on the list for the managers?

Currently the information was only displayed in the form view.
![ejemplo](https://user-images.githubusercontent.com/4117568/200284722-7a399b9d-3dcb-4faf-a604-625e7a44a4d7.gif)

2022-11-07 10:15 UTC, victoralmau commented
IMO, I think a good solution would be:

Form view:
- Add 2 embedded maps from google maps with corresponding coordinates.

Tree view:
- Add 2 fields (`geolocation_check_in` and `geolocation_check_out`) with the link to google maps with the corresponding coordinates.

What do you think about this?

2022-11-07 10:17 UTC, pedrobaeza commented
All the Google map stuff is out of scope of this module, which aim is to store the information in raw format.

2022-11-07 10:49 UTC, nimarosa commented
> IMO, I think a good solution would be:
> 
> 
> 
> Form view:
> 
> - Add 2 embedded maps from google maps with corresponding coordinates.
> 
> 
> 
> Tree view:
> 
> - Add 2 fields (`geolocation_check_in` and `geolocation_check_out`) with the link to google maps with the corresponding coordinates.
> 
> 
> 
> What do you think about this?

Looks like a good solution but like Pedro said, maybe we have to do it out of this migration PR, opening another one. I made the suggestion here to see what you guys think. 

We should do it in a new PR.

2022-11-07 12:32 UTC, victoralmau commented
Added more readable fields to list and form view.

2022-11-07 16:50 UTC, pedrobaeza commented
Fields should be only visible to managers, and `raw` is the opposite to human-readable concept. And please check that the core feature (registering the coordinates) is not working AFAIK.

2022-11-08 15:04 UTC, victoralmau commented
I have changed the way the coordinates are displayed. 
The module does allow to save the coordinates in check in and check out attendances but I think we could re-factor the javascript almost completely to reduce the code and use context to set coordinates.

2022-11-08 19:43 UTC, pedrobaeza reviewed
I'm trying on runboat and still don't get that any geolocation is logged. Firefox is not asking me to allow geolocation. Am I doing something wrong?

2022-11-08 19:43 UTC, pedrobaeza commented on hr_attendance_geolocation/models/hr_attendance.py
> +    check_in_longitude_raw = fields.Char(
This is the opposite of raw. Please call it `check_in_longitude_human` or `check_in_longitude_text` or `check_in_longitude_readable`.

2022-11-09 07:56 UTC, victoralmau commented
> I'm trying on runboat and still don't get that any geolocation is logged. Firefox is not asking me to allow geolocation. Am I doing something wrong?

Oh, I just found out that you can **only request geolocation** in the browser **if you use https**.

If you try it in localhost you can check how it works.

2022-11-09 07:57 UTC, pedrobaeza commented
Please document it on the README.

2022-11-09 08:29 UTC, pedrobaeza commented
@sbidoul putting `https` previously on the URL, it worked and get runboat HTTPS, but now it seems it's not working. Maybe this was due to the change for making it work fast? Is there any way to do it?

2022-11-09 11:49 UTC, pedrobaeza approved these changes

2022-11-09 12:09 UTC, nimarosa commented
Hello, I tested in my test instance with https and it works. I tested like 5 times. I don't know if it work always but for me and in chrome browser is working.

2022-11-09 12:10 UTC, nimarosa approved these changes

2022-11-09 12:34 UTC, pedrobaeza commented
Thanks for the extra testing, Nicolás. A pity that it can't be tested on runboat, although I'm waiting the answer from @sbidoul to see if there's any possibility.

/ocabot merge nobump

2022-11-09 12:38 UTC, sbidoul commented
> @sbidoul putting https previously on the URL, it worked and get runboat HTTPS, but now it seems it's not working. Maybe this was due to the change for making it work fast? Is there any way to do it?

Ah, that's likely a subtle behavior change between nginx and haproxy.
There is no certificate configured on the ingress, so maybe nginx used a default one.

2022-11-09 12:39 UTC, merged

2022-11-09 12:41 UTC, pedrobaeza commented
> Ah, that's likely a subtle behavior change between nginx and haproxy. There is no certificate configured on the ingress, so maybe nginx used a default one.

And is there any possibility to put a default one somehow to have HTTPS?

2022-11-09 12:42 UTC, sbidoul commented
I'll have look. Don't hold your breath, though as I'm fairly busy these days.

2022-11-09 12:47 UTC, pedrobaeza commented
Hehe, OK, your work on this is always appreciated.

2022-11-09 13:06 UTC, nimarosa commented
> @pedrobaeza The merge process could not be finalized, because command `git push origin 15.0-ocabot-merge-pr-80-by-pedrobaeza-bump-nobump:15.0` failed with output:
> ```
> To https://github.com/OCA/hr-attendance
>  ! [rejected]        15.0-ocabot-merge-pr-80-by-pedrobaeza-bump-nobump -> 15.0 (fetch first)
> error: failed to push some refs to 'https://***@github.com/OCA/hr-attendance'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.
> 
> ```

@pedrobaeza I'm seeing a lot of this errors in different PR. The bot finally makes the merge but with an error. Is this something happening in instances that is causing it? Just curious.

2022-11-09 13:08 UTC, pedrobaeza commented
I can't really say. Maybe it's due to any bot commit meanwhile. @sbidoul may have a hint.

2022-11-09 13:22 UTC, sbidoul commented
That's new to me, and we should worry about it, it's really abnormal. No time to look right now, though.

2022-11-11 09:09 UTC, sbidoul commented
You can now manually force an https URL in runboat, and if you accept the default certificate it should work.

2022-11-11 12:01 UTC, pedrobaeza commented
Thank you very much for the quick reaction, @sbidoul. Tested and working, although there's a weird initial redirection and has to be typed 2 times, but that's something of Odoo itself I think.

@victoralmau now that I have been able of testing it, the human representation puts both on longitude and latitude the word `N/S` instead of `E/W` in the second one.